packages:
  - "packages/*"
  - "api"
  - "web"
  - "companion"
  - "apps/desktop"
  - "apps/video"
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  electron: true
  electron-winstaller: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@remotion/bundler@4.0.483'
  - '@remotion/canvas-capture@4.0.483'
  - '@remotion/cli@4.0.483'
  - '@remotion/compositor-darwin-arm64@4.0.483'
  - '@remotion/compositor-darwin-x64@4.0.483'
  - '@remotion/compositor-linux-arm64-gnu@4.0.483'
  - '@remotion/compositor-linux-arm64-musl@4.0.483'
  - '@remotion/compositor-linux-x64-gnu@4.0.483'
  - '@remotion/compositor-linux-x64-musl@4.0.483'
  - '@remotion/compositor-win32-x64-msvc@4.0.483'
  - '@remotion/google-fonts@4.0.483'
  - '@remotion/licensing@4.0.483'
  - '@remotion/media-parser@4.0.483'
  - '@remotion/media-utils@4.0.483'
  - '@remotion/player@4.0.483'
  - '@remotion/renderer@4.0.483'
  - '@remotion/streaming@4.0.483'
  - '@remotion/studio-server@4.0.483'
  - '@remotion/studio-shared@4.0.483'
  - '@remotion/studio@4.0.483'
  - '@remotion/timeline-utils@4.0.483'
  - '@remotion/web-renderer@4.0.483'
  - '@remotion/zod-types@4.0.483'
  - remotion@4.0.483
