/**
 * Bot detection for review / comment bodies.
 *
 * Some maintainer accounts in this repo (e.g. mrcfps) operate partly as a
 * Looper auto-review bot — the user account is a real MEMBER but the review
 * body is generated by Looper and carries an HTML-comment stamp. We need to
 * surface that distinction because GitHub's `reviewDecision === "APPROVED"`
 * can otherwise land a PR in the `merge-ready` bucket with zero formal human
 * sign-off.
 */

const BOT_MARKERS = [
  /<!--\s*looper:/i,
  /Powered by\s*<a[^>]*>Looper<\/a>/i,
  /\[bot\]/i,
];

export function isBotAuthored(
  actor: { login: string } | null,
  body: string,
): boolean {
  if (actor && actor.login.toLowerCase().endsWith("[bot]")) return true;
  return BOT_MARKERS.some((rx) => rx.test(body));
}

export function stripBotMarkers(body: string): string {
  let stripped = body;
  stripped = stripped.replace(/<!--\s*looper:[\s\S]*?-->/gi, "");
  stripped = stripped.replace(/<sub>[\s\S]*?Looper[\s\S]*?<\/sub>/gi, "");
  return stripped.trim();
}

export function condense(body: string, max: number): string {
  const cleaned = stripBotMarkers(body).replace(/\s+/g, " ").trim();
  return cleaned.length <= max ? cleaned : `${cleaned.slice(0, max - 1)}…`;
}

/**
 * True when the PR's review-decision is APPROVED but every APPROVED-state
 * review is bot-authored — i.e. no human reviewer formally signed off. We
 * only flag when reviewDecision is APPROVED; for any other decision the
 * notion doesn't apply.
 */
export function isBotOnlyApproval(
  reviewDecision: string,
  reviews: ReadonlyArray<{ author: { login: string } | null; body: string; state: string }>,
): boolean {
  if (reviewDecision !== "APPROVED") return false;
  const approvedReviews = reviews.filter((r) => r.state === "APPROVED");
  if (approvedReviews.length === 0) return false;
  return approvedReviews.every((r) => isBotAuthored(r.author, r.body));
}

/**
 * Reduces a PR's full review history to the most recent review per reviewer
 * (by `submittedAt`). Anonymous / null-author entries are dropped. The
 * result mirrors what `gh pr view --json latestReviews` returns, except it
 * preserves the `commit.oid` field on each entry — which `latestReviews`
 * does not expose. Detectors that ask "what is each reviewer's current
 * stance?" should consume this output.
 */
export function reduceLatestReviewsByAuthor<
  T extends {
    author: { login: string } | null;
    submittedAt: string;
  },
>(history: ReadonlyArray<T>): T[] {
  const byAuthor = new Map<string, T>();
  for (const review of history) {
    const login = review.author?.login;
    if (!login) continue;
    const existing = byAuthor.get(login);
    if (!existing || existing.submittedAt < review.submittedAt) {
      byAuthor.set(login, review);
    }
  }
  return [...byAuthor.values()];
}
