import type { SimulationEdge, SimulationNode } from "@/lib/chat-parts";

export type CanvasActionBehavior =
  | "local"
  | "prompt"
  | "confirm"
  | "snapshot"
  | "pending";

export type CanvasActionRisk = "low" | "medium" | "high";
export type CanvasActionSurface = "primary" | "more" | "hidden";

export type CanvasActionContext = {
  sessionId?: string;
  roundId?: string;
  selectedNode?: SimulationNode | null;
  selectedEdge?: SimulationEdge | null;
  hasWorldModel?: boolean;
  isViewingHistoricalRound?: boolean;
  runStatus?: "running" | "completed" | "waiting_user" | "failed";
  changesCoreBoundary?: boolean;
};

export type CanvasActionDefinition = {
  actionId: string;
  label: string;
  targetKind: string;
  defaultBehaviorType: CanvasActionBehavior;
  defaultSurface: CanvasActionSurface;
  risk: CanvasActionRisk;
  createsNewRound: boolean | ((context: CanvasActionContext) => boolean);
  requiresConfirmation: boolean | ((context: CanvasActionContext) => boolean);
  resolveBehavior?: (context: CanvasActionContext) => CanvasActionBehavior;
};

function defineAction(
  definition: CanvasActionDefinition,
): CanvasActionDefinition {
  return definition;
}

export const CANVAS_ACTION_REGISTRY = {
  "prompt.reparse": defineAction({
    actionId: "prompt.reparse",
    label: "重新解析",
    targetKind: "prompt",
    defaultBehaviorType: "prompt",
    defaultSurface: "more",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "prompt.edit": defineAction({
    actionId: "prompt.edit",
    label: "修改原问题",
    targetKind: "prompt",
    defaultBehaviorType: "prompt",
    defaultSurface: "more",
    risk: "medium",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "prompt.stop": defineAction({
    actionId: "prompt.stop",
    label: "停止当前推演起点",
    targetKind: "prompt",
    defaultBehaviorType: "confirm",
    defaultSurface: "more",
    risk: "high",
    createsNewRound: false,
    requiresConfirmation: true,
  }),
  "topic.generateWorldModel": defineAction({
    actionId: "topic.generateWorldModel",
    label: "生成世界模型",
    targetKind: "topic",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "medium",
    createsNewRound: true,
    requiresConfirmation: (context) => Boolean(context.hasWorldModel),
    resolveBehavior: (context) => (context.hasWorldModel ? "confirm" : "prompt"),
  }),
  "topic.editBoundary": defineAction({
    actionId: "topic.editBoundary",
    label: "编辑边界",
    targetKind: "topic",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "medium",
    createsNewRound: (context) => Boolean(context.changesCoreBoundary),
    requiresConfirmation: (context) => Boolean(context.changesCoreBoundary),
    resolveBehavior: (context) =>
      context.changesCoreBoundary ? "confirm" : "prompt",
  }),
  "topic.addBoundaryCondition": defineAction({
    actionId: "topic.addBoundaryCondition",
    label: "补充边界条件",
    targetKind: "topic",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "topic.viewImpact": defineAction({
    actionId: "topic.viewImpact",
    label: "查看影响",
    targetKind: "topic",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "topic.continue": defineAction({
    actionId: "topic.continue",
    label: "继续推演",
    targetKind: "topic",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "topic.generateWorldModelNext": defineAction({
    actionId: "topic.generateWorldModelNext",
    label: "生成新版世界模型",
    targetKind: "topic",
    defaultBehaviorType: "confirm",
    defaultSurface: "hidden",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "history.compareLatest": defineAction({
    actionId: "history.compareLatest",
    label: "对比最新",
    targetKind: "history",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "history.backToLatest": defineAction({
    actionId: "history.backToLatest",
    label: "回到最新",
    targetKind: "history",
    defaultBehaviorType: "snapshot",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "history.continueFrom": defineAction({
    actionId: "history.continueFrom",
    label: "从此继续",
    targetKind: "history",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "scenario.continue": defineAction({
    actionId: "scenario.continue",
    label: "基于此情景继续推演",
    targetKind: "scenario",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "scenario.compareBaseline": defineAction({
    actionId: "scenario.compareBaseline",
    label: "对比 Baseline",
    targetKind: "scenario",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "scenario.counterfactual": defineAction({
    actionId: "scenario.counterfactual",
    label: "生成反事实",
    targetKind: "scenario",
    defaultBehaviorType: "confirm",
    defaultSurface: "more",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "path.continue": defineAction({
    actionId: "path.continue",
    label: "基于此路径继续推演",
    targetKind: "path",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "edge.insertNode": defineAction({
    actionId: "edge.insertNode",
    label: "边上插点",
    targetKind: "edge",
    defaultBehaviorType: "pending",
    defaultSurface: "hidden",
    risk: "medium",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "edge.manualConnect": defineAction({
    actionId: "edge.manualConnect",
    label: "手动画线",
    targetKind: "edge",
    defaultBehaviorType: "pending",
    defaultSurface: "hidden",
    risk: "medium",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "variable.viewImpact": defineAction({
    actionId: "variable.viewImpact",
    label: "查看影响",
    targetKind: "variable",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "variable.lock": defineAction({
    actionId: "variable.lock",
    label: "锁定变量",
    targetKind: "variable",
    defaultBehaviorType: "prompt",
    defaultSurface: "more",
    risk: "medium",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "variable.restoreDefault": defineAction({
    actionId: "variable.restoreDefault",
    label: "恢复为默认假设",
    targetKind: "variable",
    defaultBehaviorType: "prompt",
    defaultSurface: "more",
    risk: "medium",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "variable.recalculate": defineAction({
    actionId: "variable.recalculate",
    label: "确认并生成新 Round",
    targetKind: "variable",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "node.expand": defineAction({
    actionId: "node.expand",
    label: "沿此节点展开",
    targetKind: "node",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "node.copy": defineAction({
    actionId: "node.copy",
    label: "复制节点信息",
    targetKind: "node",
    defaultBehaviorType: "local",
    defaultSurface: "more",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "risk.addMitigation": defineAction({
    actionId: "risk.addMitigation",
    label: "加入缓释措施",
    targetKind: "risk",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "risk.warningVariable": defineAction({
    actionId: "risk.warningVariable",
    label: "生成预警变量",
    targetKind: "risk",
    defaultBehaviorType: "confirm",
    defaultSurface: "more",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "risk.stressTest": defineAction({
    actionId: "risk.stressTest",
    label: "压力测试",
    targetKind: "risk",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "event.assumeHappens": defineAction({
    actionId: "event.assumeHappens",
    label: "假设发生",
    targetKind: "event",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "event.assumeNotHappens": defineAction({
    actionId: "event.assumeNotHappens",
    label: "假设未发生",
    targetKind: "event",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "action.simulate": defineAction({
    actionId: "action.simulate",
    label: "模拟执行",
    targetKind: "action",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "action.compareNotDoing": defineAction({
    actionId: "action.compareNotDoing",
    label: "对比不执行",
    targetKind: "action",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "action.edit": defineAction({
    actionId: "action.edit",
    label: "修改行动",
    targetKind: "action",
    defaultBehaviorType: "prompt",
    defaultSurface: "more",
    risk: "medium",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "action.addCondition": defineAction({
    actionId: "action.addCondition",
    label: "补充执行条件",
    targetKind: "action",
    defaultBehaviorType: "prompt",
    defaultSurface: "more",
    risk: "medium",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "action.evaluateSideEffects": defineAction({
    actionId: "action.evaluateSideEffects",
    label: "评估副作用",
    targetKind: "action",
    defaultBehaviorType: "prompt",
    defaultSurface: "more",
    risk: "medium",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "entity.addVariable": defineAction({
    actionId: "entity.addVariable",
    label: "补充变量",
    targetKind: "entity",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "entity.addEvent": defineAction({
    actionId: "entity.addEvent",
    label: "补充事件",
    targetKind: "entity",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "entity.analyzeRelation": defineAction({
    actionId: "entity.analyzeRelation",
    label: "分析关系",
    targetKind: "entity",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "decision.compareBranches": defineAction({
    actionId: "decision.compareBranches",
    label: "比较分支",
    targetKind: "decision",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "decision.defer": defineAction({
    actionId: "decision.defer",
    label: "暂缓决策",
    targetKind: "decision",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "medium",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "decision.addVariable": defineAction({
    actionId: "decision.addVariable",
    label: "补充决策变量",
    targetKind: "decision",
    defaultBehaviorType: "prompt",
    defaultSurface: "more",
    risk: "medium",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "decision.selectBranch": defineAction({
    actionId: "decision.selectBranch",
    label: "选择决策分支",
    targetKind: "decision",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "hypothesis.replace": defineAction({
    actionId: "hypothesis.replace",
    label: "替换假设",
    targetKind: "hypothesis",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "hypothesis.lock": defineAction({
    actionId: "hypothesis.lock",
    label: "锁定假设",
    targetKind: "hypothesis",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: false,
    requiresConfirmation: true,
  }),
  "hypothesis.delete": defineAction({
    actionId: "hypothesis.delete",
    label: "请求删除假设",
    targetKind: "hypothesis",
    defaultBehaviorType: "confirm",
    defaultSurface: "more",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "hypothesis.branch": defineAction({
    actionId: "hypothesis.branch",
    label: "生成分支",
    targetKind: "hypothesis",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "inference.viewEvidence": defineAction({
    actionId: "inference.viewEvidence",
    label: "查看证据",
    targetKind: "inference",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "inference.recalculate": defineAction({
    actionId: "inference.recalculate",
    label: "重新推理",
    targetKind: "inference",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "inference.counterEvidence": defineAction({
    actionId: "inference.counterEvidence",
    label: "寻找反证",
    targetKind: "inference",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "conclusion.challenge": defineAction({
    actionId: "conclusion.challenge",
    label: "挑战结论",
    targetKind: "conclusion",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "conclusion.refute": defineAction({
    actionId: "conclusion.refute",
    label: "要求反驳",
    targetKind: "conclusion",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "conclusion.report": defineAction({
    actionId: "conclusion.report",
    label: "生成报告段落",
    targetKind: "conclusion",
    defaultBehaviorType: "prompt",
    defaultSurface: "more",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "evidence.verify": defineAction({
    actionId: "evidence.verify",
    label: "核验证据",
    targetKind: "evidence",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "evidence.locateCitation": defineAction({
    actionId: "evidence.locateCitation",
    label: "定位引用",
    targetKind: "evidence",
    defaultBehaviorType: "prompt",
    defaultSurface: "more",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "evidence.locateSource": defineAction({
    actionId: "evidence.locateSource",
    label: "请求定位原文",
    targetKind: "evidence",
    defaultBehaviorType: "prompt",
    defaultSurface: "more",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "evidence.counterExample": defineAction({
    actionId: "evidence.counterExample",
    label: "查找反例",
    targetKind: "evidence",
    defaultBehaviorType: "confirm",
    defaultSurface: "more",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "evidence.replace": defineAction({
    actionId: "evidence.replace",
    label: "寻找替代证据",
    targetKind: "evidence",
    defaultBehaviorType: "confirm",
    defaultSurface: "more",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "evidence.supplement": defineAction({
    actionId: "evidence.supplement",
    label: "补充证据",
    targetKind: "evidence",
    defaultBehaviorType: "confirm",
    defaultSurface: "more",
    risk: "medium",
    createsNewRound: false,
    requiresConfirmation: true,
  }),
  "summary.followUp": defineAction({
    actionId: "summary.followUp",
    label: "继续追问",
    targetKind: "summary",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "summary.generateReport": defineAction({
    actionId: "summary.generateReport",
    label: "生成报告",
    targetKind: "summary",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "summary.extractNextActions": defineAction({
    actionId: "summary.extractNextActions",
    label: "提取 Next Action",
    targetKind: "summary",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "suggestion.continue": defineAction({
    actionId: "suggestion.continue",
    label: "基于建议继续",
    targetKind: "suggestion",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "deliverables.updateReport": defineAction({
    actionId: "deliverables.updateReport",
    label: "更新报告",
    targetKind: "deliverables",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "deliverables.deckOutline": defineAction({
    actionId: "deliverables.deckOutline",
    label: "生成演示稿大纲",
    targetKind: "deliverables",
    defaultBehaviorType: "prompt",
    defaultSurface: "more",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "deliverables.extractSummary": defineAction({
    actionId: "deliverables.extractSummary",
    label: "提取摘要",
    targetKind: "deliverables",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "recovery.retryRound": defineAction({
    actionId: "recovery.retryRound",
    label: "重试本轮",
    targetKind: "recovery",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "medium",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "recovery.viewSaved": defineAction({
    actionId: "recovery.viewSaved",
    label: "查看已保存内容",
    targetKind: "recovery",
    defaultBehaviorType: "prompt",
    defaultSurface: "primary",
    risk: "low",
    createsNewRound: false,
    requiresConfirmation: false,
  }),
  "recovery.restartFromSnapshot": defineAction({
    actionId: "recovery.restartFromSnapshot",
    label: "基于快照重新开始",
    targetKind: "recovery",
    defaultBehaviorType: "confirm",
    defaultSurface: "more",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
  "nextAction.execute": defineAction({
    actionId: "nextAction.execute",
    label: "执行 Next Action",
    targetKind: "next_action",
    defaultBehaviorType: "confirm",
    defaultSurface: "primary",
    risk: "high",
    createsNewRound: true,
    requiresConfirmation: true,
  }),
} satisfies Record<string, CanvasActionDefinition>;

export type CanvasActionId = keyof typeof CANVAS_ACTION_REGISTRY;

export function getCanvasActionDefinition(
  actionId?: string | null,
): CanvasActionDefinition | undefined {
  if (!actionId) return undefined;
  return CANVAS_ACTION_REGISTRY[actionId as CanvasActionId];
}

export function resolveCanvasActionBehavior(
  actionId: string,
  context: CanvasActionContext = {},
): CanvasActionBehavior | undefined {
  const definition = getCanvasActionDefinition(actionId);
  if (!definition) return undefined;
  return definition.resolveBehavior?.(context) ?? definition.defaultBehaviorType;
}

export function resolveCanvasActionCreatesNewRound(
  actionId: string,
  context: CanvasActionContext = {},
): boolean | undefined {
  const definition = getCanvasActionDefinition(actionId);
  if (!definition) return undefined;
  return typeof definition.createsNewRound === "function"
    ? definition.createsNewRound(context)
    : definition.createsNewRound;
}

export function resolveCanvasActionRequiresConfirmation(
  actionId: string,
  context: CanvasActionContext = {},
): boolean | undefined {
  const definition = getCanvasActionDefinition(actionId);
  if (!definition) return undefined;
  return typeof definition.requiresConfirmation === "function"
    ? definition.requiresConfirmation(context)
    : definition.requiresConfirmation;
}
